#!/bin/sh
# Xcode Cloud post-clone: recreate the gitignored Secrets.xcconfig from workflow
# environment variables, and install sentry-cli for the dSYM upload script phase.
#
# Expected environment variables (set in the Xcode Cloud workflow):
#   SENTRY_DSN         - plain DSN, e.g. https://abc123@o123.ingest.de.sentry.io/456
#                        (this script converts // to the $()/  xcconfig escape)
#   SENTRY_AUTH_TOKEN  - mark as SECRET in Xcode Cloud (scopes: project:releases, project:write)
#   SENTRY_ORG         - org slug (iamjarl)
#   SENTRY_PROJECT     - project slug (ironworkout-ios)
#
# Everything degrades gracefully: without the variables the app builds and ships
# without Sentry, and the upload phase skips itself (see Scripts/sentry-upload-dsyms.sh).

set -u

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/Iron Workout/Config/Secrets.xcconfig"

if [ -n "${SENTRY_DSN:-}" ]; then
    # xcconfig treats // as a comment, so escape the scheme separator.
    ESCAPED_DSN=$(printf '%s' "$SENTRY_DSN" | sed 's|://|:/$()/|')
    {
        echo "// Generated by ci_scripts/ci_post_clone.sh (Xcode Cloud) — do not edit."
        echo "SENTRY_DSN = $ESCAPED_DSN"
        [ -n "${SENTRY_AUTH_TOKEN:-}" ] && echo "SENTRY_AUTH_TOKEN = $SENTRY_AUTH_TOKEN"
        [ -n "${SENTRY_ORG:-}" ] && echo "SENTRY_ORG = $SENTRY_ORG"
        [ -n "${SENTRY_PROJECT:-}" ] && echo "SENTRY_PROJECT = $SENTRY_PROJECT"
    } > "$SECRETS_FILE"
    echo "Secrets.xcconfig generated (DSN set, dSYM upload $([ -n "${SENTRY_AUTH_TOKEN:-}" ] && echo enabled || echo disabled))."
else
    echo "note: SENTRY_DSN not set — building without Sentry (crash reporting disabled in this build)."
fi

# sentry-cli for the archive-time dSYM upload phase (best effort; the phase skips if absent).
if [ -n "${SENTRY_AUTH_TOKEN:-}" ] && ! command -v sentry-cli >/dev/null 2>&1; then
    echo "Installing sentry-cli via Homebrew..."
    brew install sentry-cli || echo "warning: sentry-cli install failed — dSYM upload will be skipped."
fi

exit 0
